import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { Krona_One, Montserrat } from "next/font/google";
import { cookies } from "next/headers";
import { axiosClient } from "@/shared/api/axios";
import Toast from "@/shared/lib/toast/toast";
import { ProgressBar } from "@/shared/lib/ProgressBar";
import QueryProvider from "@/core/providers/query/QueryProvider";
import { TooltipProvider } from "@radix-ui/react-tooltip";

const montserrat = Montserrat({ subsets: ["latin"] });
const kronaOne = Krona_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kronaOne",
});

export const metadata: Metadata = {
  title: "Smart Money - Smart Investment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  axiosClient.interceptors.request.use((cfg) => {
    const token = cookies().get("token")?.value;
    cfg.headers["Authorization"] = `Bearer ${token}`;
    return cfg;
  });

  return (
    <html lang="en">
      <QueryProvider>
        <TooltipProvider>
          <body
            className={cn(
              montserrat.className,
              kronaOne.variable,
              "antialiased",
            )}
          >
            <Toast />
            <ProgressBar />
            {children}
          </body>
        </TooltipProvider>
      </QueryProvider>
    </html>
  );
}
